### ISSUE TITLE
error in computing depth_grad_2?

### ISSUE THREAD

**Issue by qiminchen** [udaykusupati/Normal-Assisted-Stereo#10]
Hi, shouldn't `c_x` and `c_y` here be the `u_c` and `v_c` of the intrinsic matrix according to equation 7 in the paper?
https://github.com/udaykusupati/Normal-Assisted-Stereo/blob/491c0d3d2efd0e6c9f97cf84b1688266b9c201d6/models/ConsModule.py#L52-L53

**Comment by udaykusupati** [comment]
Thank you very much for pointing this out, I think you are right and this makes a difference when we are doing RandomScaleCrop during train time. You can use the intrinsic_var supplied to the function. I will update the code after I take a closer look at what was going on there.
