### ISSUE TITLE
how did you obtain the normal data for scannet?

### ISSUE THREAD

**Issue by hua-wu-que** [udaykusupati/Normal-Assisted-Stereo#14]
Hi,
Could you elaborate on what is the algorithm you used to obtain the normal ground truth for these datasets? for example scannet/sun3d. Appreciate it a lot!

**Comment by udaykusupati** [comment]
As mentioned in Section 4.1, we generate GT normal data as others using the method mentioned in [13] (Refer main paper [bibliography)](https://arxiv.org/pdf/1911.10444.pdf)
