### ISSUE TITLE
Details of Table1 in paper

### ISSUE THREAD

**Issue by makeastir** [udaykusupati/Normal-Assisted-Stereo#15]
@udaykusupati 

I has questions about Table 1.
```
MVS    A.Rel  A.diff Sq.Rel   a=1    a=2    a=3
Paper  0.0679 0.1677 0.0555 0.9054 0.9644 0.9879
```

When testing this quantitative measure, Did you trained MVDNet using DeMoN dataset and Consistency module trained using MVS Datasets only?

Similarly, others dataset also trained MVDNet using DeMoN dataset and Consistency module trained specific datasets only ?
Or, trained MVDNet and Consistency module through DeMoN and evaluated each datasets ?

_Originally posted by @makeastir in https://github.com/udaykusupati/Normal-Assisted-Stereo/issues/12#issuecomment-704201862_

**Comment by udaykusupati** [comment]
Table 1 is evaluation of MVDNet alone and there is no consistency module used. We train MVDNet jointly on all DeMoN datasets and provide evaluations on each of the individual sub-datasets.
For consistency module, we train the entire pipeline using a single dataset (SUN3D or Scannet)
