### ISSUE TITLE
pretrained model are not available

### ISSUE THREAD

**Issue by Qianqian3764** [udaykusupati/Normal-Assisted-Stereo#21]
Dear author, 
 Thanks for your work! 
 When I reproduce the results in the paper, I found that link  'https://drive.google.com/drive/folders/1PTi37xlPxqhHNyxs_4xiGGj1OsnTQhWD?usp=sharing' is empty. Could you share permissions on the project?
 Thanks!!
![image](https://user-images.githubusercontent.com/10708893/209446115-1ca5e3e5-1081-43b3-bd94-fb2b1befe96a.png)

**Comment by udaykusupati** [comment]
They should be available now :)
