### ISSUE TITLE
Cannot Download Scannet + Normals

### ISSUE THREAD

**Issue by dlichy** [udaykusupati/Normal-Assisted-Stereo#22]
Hi,

When I try to download the file [scannet.tar.gz](https://drive.google.com/drive/folders/1PTi37xlPxqhHNyxs_4xiGGj1OsnTQhWD?usp=sharing) it says "This folder is empty". Is it still possible to obtain the datasets?

Thanks,
Daniel

**Comment by udaykusupati** [comment]
I am sorry, we suffered a data loss. I am still trying to recover the training data, and will update the repo if/when possible.

**Comment by yotofu** [comment]
Hi, is it OK now to download the https://drive.google.com/drive/folders/1PTi37xlPxqhHNyxs_4xiGGj1OsnTQhWD?usp=sharing?
