### ISSUE TITLE
Surface normal construction

### ISSUE THREAD

**Issue by SamChuah** [udaykusupati/Normal-Assisted-Stereo#3]
Hi interesting work you've got here! 
By any chance will you share the surface normal generation script? 
Thank you

**Comment by MurrayC7** [comment]
@udaykusupati Hi, I also wish to figure out the surface normal generation in the codebase. Or, could you please share the surface normal groundtruth for KITTI datasets? :)

**Comment by udaykusupati** [comment]
I have added the normal generation script (convert_normal.py). Apologies for the delay.
