### ISSUE TITLE
Confusing conversion between disparity and depth.

### ISSUE THREAD

**Issue by MurrayC7** [udaykusupati/Normal-Assisted-Stereo#4]
Hello, thanks for opening the excellent work to the public!
When using the code, I have confused about the conversion between disparity and depth in the code.

1. For sceneflow, firstly its disparity is converted to the depth at [data_loader.py](https://github.com/udaykusupati/Normal-Assisted-Stereo/blob/master/data_loader.py#L299). Then, the depth is corrected at [train_sflow.py](https://github.com/udaykusupati/Normal-Assisted-Stereo/blob/master/train_sflow.py#L295) because of different focal length, where my confusion is.
Could you please help me to understand the meaning of `(args.mindepth*factor)*(args.nlabel*3)/disp`, or the meaning of `minidepth` and `nlabel`? Similar conversion is likely at [MVDNet.py](https://github.com/udaykusupati/Normal-Assisted-Stereo/blob/master/models/MVDNet.py#L155). Since I only know the equation `depth = focal_length * baseline / disparity`,  where the focal_length is 450 or 1050 units from the intrinsics and the baseline is 1.0 Blender units from [sceneflow website](https://lmb.informatik.uni-freiburg.de/resources/datasets/SceneFlowDatasets.en.html), but `minidepth` is 5.45 and nlabel is 64.

2. For KITTI, its disparity seems only to be divided by 256.0 [data_loader.py](https://github.com/udaykusupati/Normal-Assisted-Stereo/blob/master/data_loader.py#L309), and I can't find any else conversions to the depth. Could you please tell me this difference? 

Thank you!

Best Wishes

**Comment by udaykusupati** [comment]
For sceneflow, the dataset contains instances with different focal lengths 450/1050. Because we compare our work with GANet, we set the max-disparity to 192, but use 64 equally spaced levels (since we have memory constraints), so mindepth = f/192, but since different instances have different focal lengths (the majority having 1050), we set f=1050. During train time, when an instance with f = 450 arrives, we need to adjust the mindepth, depending on the intrinsics, which the factor takes care of. Finally, args.nlabel*3 is just 192.

For kitti we have a constant focal length across all instances, so this problem doesn't arise.

**Comment by MurrayC7** [comment]
Thanks for the clear explanation!
For KITTI, I wonder what constant you use. By the way, there are different intrinsics in KITTI instances, but it seems there isn't a use of intrinsics like that use in [sceneflow](https://github.com/udaykusupati/Normal-Assisted-Stereo/blob/master/data_loader.py#L299). Maybe, do you mean the depths are converted before loading data?

**Comment by udaykusupati** [comment]
Sorry KITTI does have different intrinsics for different instances. I stand corrected. The train file should be modified exactly similar to sceneflow, where the factor will take care of the appropriate conversion. For both KITTI datasets, I set mindepth = 2.029 and use 

> factor = (1.0/args.scale)*intrinsics_var[:,0,0]/721.5377

I didn't include KITTI training in the code released so as to not increase confusion, but these changes should help you train KITTI.

**Comment by MurrayC7** [comment]
Okay, I see. Thanks a million for clarification!
