### ISSUE TITLE
Additional requirement: PreTrained Model for kitti dataset

### ISSUE THREAD

**Issue by TWJianNuo** [udaykusupati/Normal-Assisted-Stereo#5]
Exellent work not only for performance and novelty, but also the high-quality codebase which benefits the whole coomunity!

I wish to do some comparison and further research into Recent work's surface normal prediciton quality in Kitti dataset. Is that possible that you can publish your model in supp material trained for kitti dataset? Testing Code alone will be of great help!

Thanks!

**Comment by udaykusupati** [comment]
I added a kitti pretrained model in the pretrained folder. The train/test code will be similar to that of sceneflow and as mentioned [https://github.com/udaykusupati/Normal-Assisted-Stereo/issues/4](here)

**Comment by TWJianNuo** [comment]
Thanks so much for your support!
