### ISSUE TITLE
Test on ETH3D dataset and DTU dataset

### ISSUE THREAD

**Issue by CanCanZeng** [udaykusupati/Normal-Assisted-Stereo#6]
Hi, thank you for opening this project.
I'm very confused that why some CNN based depth estimation methods will test on DTU dataset or Tanks and Temples dataset (mvsnet, cas-mvsnet), while some others will demonstrate their accuracy on ETH3D dataset (DPSNet, DeepMVS). Then your method show the results on DeMoN and ScanNet dataset, how can these method compete which each other?
Or are these methods dealing with different problem but I'm not aware?

**Comment by udaykusupati** [comment]
Recent stereo works can be broadly classified into two depending on the end-goal, accurate 3d reconstructions of an object in question given multiple views, or better depth estimation of a scene as views become increasingly available (but mostly we might end up with just two views). Broadly speaking, both kinds of works should be cross-applicable and the problem isn't fundamentally different, but we constrained ourselves to the target application of improving depth estimation. So we evaluate over scene datasets like DeMoN and one particular reason to use ScanNet is to demonstrate our multi-view normal estimation benefits compared to single-view methods on a dataset that provides stereo input.

**Comment by cvgogogo** [comment]
Hi, I am a bit confused either. In my opinion, datasets like KITTI are widely research, but papers like DPSNet do not consider them. In addition,  I agree to the your idea that the problem isn't fundamentally different. Thus, I wonder the accuray of 3d reconstruction models using depth estimations in your paper. Have you done some related experiments ? Thanks!
