### ISSUE TITLE
no 'val' folder in new_orders.zip

### ISSUE THREAD

**Issue by hua-wu-que** [udaykusupati/Normal-Assisted-Stereo#8]
Hi,

I tried to launch training with 

python train.py ./scannet --dataset scannet --mindepth 0.25

The error is:
"scannet/new_orders/val/valnew_orders_v.list not found"

Then I found out new_orders folder only contains train/test folder

**Comment by udaykusupati** [comment]
Hi. 
I went through this and there seems to be some confusion created by me. I apologize for this. 
Answering your other question first, I see and I will upload the test directory. Btw, you can ignore the .list files in the scannet folder. They serve no purpose.
The test split we use has all its files in the val folder. So if you just need to train and test, the train, val folders in scannet are sufficient. For the val split, I need to upload the orders. Instead I can just upload the .pkl file [here](https://drive.google.com/file/d/1qDXBhO5l3rGT0h-AuCnUemSiQADLheT0/view?usp=sharing) for your use before I make these changes more concretely in the repo.(). But these val list I uploaded actually has its files in the test folder of scannet which I need to upload first. 
We made our train/test/val splits first and later had to adapt to a previous work's splits causing this confusion. Again, if you just need to train to some fixed epochs and test, you can do it now without any new uploads from me. 
Once again, I apologize for the confusion.
